title: Ein Titel
author: Author
email: test@test.de
description: > # this means to ignore newlines until "show_exerpts:"
  Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est .

show_excerpts: false # set to true to show excerpts on the homepage

pub:
  pdf: /fake/link/to.pdf
mainpage:
  url: //your-actual-website.tld
  label: Go back to your actual website
  year: 2018
chapter:
  effects:
    - label: Das Problem
      key: problem
    - label: Lösungsansatz
      key: solution
    - label: Angestrebte Wirkung
      key: effect
  resources:
    - label: Projektlaufzeit
      key: timespan
    - label: Finanzierung
      key: funding
  outcomes:
    - label: Erbrachte Leistungen
      key: achievements
    - label: Output
      key: outputs
    - label: Outcome
      key: outcome
    - label: Evaluation und Ausblick
      key: evaluation

# matomo:
#   url: //to-your-matomo.tdl
#   id: projectID

# Build settings
theme: okf-pub-theme

plugins:
 - jekyll-feed
 - jekyll-seo-tag
